# Generated by Django 4.0.2 on 2022-02-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Обложка поста')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок статьи')),
                ('content', models.TextField(verbose_name='Содержание поста')),
                ('author', models.CharField(default='SVDe', max_length=100, verbose_name='Автор поста')),
                ('date', models.DateTimeField(verbose_name='Время публикации')),
                ('category', models.ManyToManyField(to='index.Category', verbose_name='Категория поста')),
            ],
            options={
                'verbose_name': 'посты',
                'verbose_name_plural': 'пост',
            },
        ),
    ]
